<?php
/**
 * V4 Company — Redirecionamentos 301 (URLs antigas -> novas)
 * Motivo: recuperacao de trafego de imagens apos migracao | 25/08/2026
 * 81 rotas — desativar este snippet para reverter tudo de uma vez.
 */
add_action('template_redirect', function () {
    static $map = [
	'empresa-fundicao' => '/empresa/',
	'fundicao-pecas-ferro-fundido' => '/fundicao-de-pecas-em-ferro-fundido/',
	'fundicao-ferro-fundido-nodular' => '/fundicao-de-ferro-cinzento-e-nodular/',
	'anel-segmento-cilindro-hidraulico' => '/produto/aneis-de-segmento/',
	'anel-segmento-compressor-ar' => '/anel-de-segmento-para-compressor/',
	'polia-elevador' => '/produto/polia-de-elevador/',
	'empresa-fundicao-ferro-fundido' => '/empresa-de-fundicao-de-ferro-fundido/',
	'cabecote-compressor-ar' => '/cabecote-compressor-de-ar/',
	'fabricante-aneis-segmento' => '/fabricante-aneis-de-segmento/',
	'aneis-pistao-compressor' => '/aneis-de-segmento-pistao/',
	'fundicao-cold-box' => '/fundicao-de-ferro-em-pep-set/',
	'aneis-segmento' => '/produto/aneis-de-segmento/',
	'blog/fundicao-de-ferro/ferro-fundido-cinzento' => '/fundicao-ferro-fundido-cinzento/',
	'fundicao-pecas-aco' => '/produto/fundicao-de-pecas-em-ferro-fundido/',
	'empresa-fundicao-sp' => '/empresa/',
	'tirante-elevador' => '/produto/tirante-para-elevador/',
	'fundicao-ferro-fundido-sp' => '/fundicao-de-ferro-fundido/',
	'aneis-compressor-ar' => '/anel-de-segmento-para-compressor/',
	'blog/aneis-de-segmento/aneis-de-segmento-pistao' => '/aneis-de-segmento-pistao/',
	'abracadeira-concreto' => '/abracadeira-para-concreto/',
	'qualidade' => '/empresa/',
	'blog/aneis-de-segmento/anel-de-segmento' => '/anel-de-segmento/',
	'blog/abracadeiras' => '/abracadeira-para-concreto/',
	'servico-fundicao' => '/servico-de-fundicao-em-sao-paulo/',
	'blog/fundicao-de-ferro/fundicao-de-ferro-fundido-sp' => '/fundicao-de-ferro-fundido/',
	'blog/aneis-de-segmento/aneis-de-segmento-do-pistao' => '/aneis-de-segmento-do-pistao/',
	'blog/aneis-de-segmento/anel-de-segmento-para-compressor' => '/anel-de-segmento-para-compressor/',
	'blog/aneis-de-segmento/aneis-de-segmento-de-ferro' => '/aneis-de-segmento-de-ferro/',
	'blog/fundicao-de-ferro/pecas-de-ferro-fundido' => '/fundicao-de-pecas-em-ferro-fundido/',
	'fundicao-pecas-automotivas' => '/categoria-produto/automotivo/',
	'porca-carcaca' => '/produto/porca-do-cardan/',
	'porca-cardan' => '/produto/porca-do-cardan/',
	'blog/fundicao-de-ferro/fundicao-de-pecas-em-ferro-fundido' => '/fundicao-de-pecas-em-ferro-fundido/',
	'blog/aneis-de-segmento/aneis-para-bombas-a-vacuo' => '/aneis-para-bombas-a-vacuo/',
	'fundicao-ferro-sp' => '/servico-de-fundicao-em-sao-paulo/',
	'fundicao-auto-pecas' => '/fundicao-de-auto-pecas/',
	'blog/fundicao-de-ferro/fundicao-ferro-fundido-cinzento' => '/fundicao-ferro-fundido-cinzento/',
	'blog/aneis-de-segmento/aneis-de-segmento-sob-medida' => '/aneis-de-segmento-sob-medida/',
	'blog/fundicao-de-ferro/fundicao-de-auto-pecas' => '/fundicao-de-auto-pecas/',
	'blog/fundicao-de-ferro/fabricacao-de-pecas-em-ferro-fundido' => '/fundicao-de-pecas-em-ferro-fundido/',
	'blog/aneis-de-segmento/anel-de-segmento-do-motor' => '/anel-de-segmento-do-motor/',
	'fundicao-pecas-compressores' => '/produto/fundicao-pecas-agricolas/',
	'polia-ferro-fundido' => '/produto/polia-de-elevador/',
	'blog/fundicao-de-ferro/fundicao-de-ferro-em-pep-set' => '/fundicao-de-ferro-em-pep-set/',
	'fabrica-aneis-compressores' => '/fabricante-aneis-de-segmento/',
	'blog/fundicao-de-ferro/fundicao-de-ferro-em-itaquaquecetuba-sp' => '/fundicao-de-ferro-em-itaquaquecetuba/',
	'fundicao-ferro-cinzento-nodular' => '/fundicao-de-ferro-cinzento-e-nodular/',
	'blog/aneis-de-segmento/anel-de-segmento-em-ferro-fundido' => '/anel-de-segmento-em-ferro-fundido/',
	'blog/fundicao-de-ferro/fundicao-de-ferro-cinzento-e-nodular' => '/fundicao-de-ferro-cinzento-e-nodular/',
	'blog/fundicao-de-ferro/fundicao-em-sao-paulo' => '/servico-de-fundicao-em-sao-paulo/',
	'blog/mancais-e-cubo/cubos-e-mancais-para-maquinas' => '/cubos-e-mancais-para-maquinas/',
	'fabrica-aneis-segmento' => '/fabricante-aneis-de-segmento/',
	'blog/fundicao-de-ferro/fundicao-de-ferros' => '/fundicao-de-ferros/',
	'blog/aneis-de-segmento/anel-de-segmento-preco' => '/anel-de-segmento-preco/',
	'blog/cabecotes/camisa-compressor' => '/camisa-compressor/',
	'blog/mancais-e-cubo' => '/cubos-e-mancais-para-maquinas/',
	'blog/fundicao-de-ferro/servico-de-fundicao-em-sao-paulo' => '/servico-de-fundicao-em-sao-paulo/',
	'blog/cilindros/cilindro-compressor-de-ar' => '/cilindro-compressor-de-ar/',
	'blog/pecas-automotivas/fabrica-de-roldanas' => '/fabrica-de-roldanas/',
	'blog/fundicao-de-ferro/fundicao-de-autopecas' => '/fundicao-de-autopecas/',
	'blog/fundicao-de-ferro/preco-do-ferro-fundido-kg' => '/preco-do-ferro-fundido-kg/',
	'blog/bombeamento-de-concreto/pecas-para-sistema-de-bombeamento-de-concreto' => '/pecas-para-sistema-de-bombeamento-de-concreto/',
	'blog/cabecotes/cabecote-para-compressor' => '/cabecote-para-compressor/',
	'blog/aneis-de-segmento/aneis-de-segmento-em-bronze' => '/aneis-de-segmento-em-bronze/',
	'blog/bombeamento-de-concreto/pecas-para-bomba-de-concreto' => '/pecas-para-bombeamento-de-concreto/',
	'blog/bombeamento-de-concreto' => '/pecas-para-bombeamento-de-concreto/',
	'blog/fundicao-de-ferro/fundicao-de-ferro-fundido' => '/fundicao-de-ferro-fundido/',
	'blog/cabecotes/cabecote-compressor-de-ar' => '/cabecote-compressor-de-ar/',
	'blog/pecas-automotivas/industria-metalurgica-de-pecas-automotivas' => '/industria-metalurgica-de-pecas-automotivas/',
	'blog/fundicao-de-ferro/fundicao-e-usinagem-em-ferro-fundido-empresa' => '/fundicao-e-usinagem-em-ferro-fundido-empresa/',
	'blog/bombeamento-de-concreto/pecas-para-bombeamento-de-concreto' => '/pecas-para-bombeamento-de-concreto/',
	'blog/fundicao-de-ferro/empresa-de-ferro-fundido' => '/empresa-de-fundicao-de-ferro-fundido/',
	'blog/pecas-para-tratores/pecas-para-tratores-agricolas' => '/pecas-para-tratores-agricolas/',
	'blog/vanderlei-rampasso' => '/blog/',
	'blog/fundicao-de-ferro/fundicao-e-usinagem' => '/fundicao-de-ferro-cinzento-e-nodular/',
	'blog/abracadeiras/abracadeira-para-concreto' => '/abracadeira-para-concreto/',
	'blog/fundicao-de-ferro/empresa-de-fundicao-de-ferro-fundido' => '/empresa-de-fundicao-de-ferro-fundido/',
	'blog/bombeamento-de-concreto/fabricante-de-pecas-para-maquinas-e-equipamentos' => '/fabricante-de-pecas-para-maquinas-e-equipamentos/',
	'blog/aneis-de-segmento/aneis-de-segmento-para-amortecedores-em-bronze' => '/aneis-de-segmento-para-amortecedores-em-bronze/',
	'blog/fundicao-de-ferro/preco-ferro-fundido' => '/fundicao-de-ferro-fundido/',
	'blog/pecas-automotivas/fabricante-de-pecas-automotivas' => '/fabricante-de-pecas-automotivas/',
    ];

    $path = strtolower( trim( (string) parse_url( isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '', PHP_URL_PATH ), '/' ) );

    if ( $path !== '' && isset( $map[ $path ] ) ) {
        wp_redirect( $map[ $path ], 301 );
        exit;
    }
} );
