ARTICLES.append((12, "fabricante-automotivo", "Fabricante automotivo de peças em ferro fundido: como selecionar o parceiro ideal", [
    ("Critérios de qualificação técnica para fornecedores automotivos",
     "A seleção de um fabricante automotivo de peças em ferro fundido exige análise criteriosa de sua capacidade técnica. O primeiro filtro envolve a certificação IATF 16949, que atesta que o processo produtivo segue os padrões rígidos da indústria automotiva. Sem essa certificação, o fornecedor não consegue atender às exigências de montadoras e sistemistas. Além disso, é fundamental verificar o controle estatístico de processo (CEP) implementado na fundição, pois peças automotivas demandam tolerâncias dimensionais apertadas, frequentemente na faixa de ±0,05 mm. A rastreabilidade total do lote, desde a análise química do metal líquido até o ensaio não destrutivo final, também é critério eliminatório."),
    ("Capacidade produtiva e prazos de entrega na cadeia automotiva",
     "Na indústria automotiva, atrasos na entrega de peças fundidas podem parar uma linha de montagem inteira, gerando prejuízos multimilionários. Por isso, o fabricante automotivo escolhido deve comprovar capacidade produtiva compatível com o volume contratado, incluindo planos de contingência para manutenção de fornos e equipamentos. É recomendável visitar a fundição para avaliar o número de linhas de moldagem, a capacidade de fusão em toneladas por dia e a disponibilidade de estoque regulador. O parceiro ideal opera com sistema kanban ou just-in-sequence, sincronizado com a demanda do cliente, e mantém um indicador de OTIF (On Time In Full) acima de 98%."),
    ("Metalurgia e ligas especiais para aplicações automotivas",
     "Peças automotivas em ferro fundido exigem domínio metalúrgico avançado, pois cada componente demanda uma composição química específica. Blocos de motor utilizam ferro fundido cinzento GG25 ou GGV30 com grafita lamelar, enquanto cabeçotes e discos de freio podem requerer ferro nodular com matriz perlítica para maior resistência ao desgaste. O fabricante automotivo ideal possui laboratório de espectrometria próprio para análise em tempo real da composição química do metal líquido, além de controle rigoroso de temperatura de vazamento e taxa de resfriamento. A capacidade de desenvolver ligas personalizadas, ajustando teores de carbono equivalente, silício e elementos de liga, diferencia os fornecedores de alto nível."),
    ("Ensaios não destrutivos e garantia de conformidade",
     "A conformidade dimensional e metalúrgica de peças automotivas em ferro fundido é validada por uma bateria de ensaios não destrutivos. A inspeção por líquido penetrante identifica trincas superficiais, enquanto o ensaio por partículas magnéticas detecta descontinuidades subsuperficiais em peças ferromagnéticas. O ultrassom industrial mede espessuras de parede e identifica vazios internos sem danificar a peça. O fabricante automotivo qualificado documenta cada ensaio em relatórios individuais, garantindo rastreabilidade por número de série. Essa documentação é essencial para o PPAP (Production Part Approval Process) exigido por montadoras, assegurando que cada lote entregue é idêntico ao aprovado na fase de protótipo."),
    ("Parceria de longo prazo e melhoria contínua",
     "A relação entre montadora e fabricante automotivo de peças em ferro fundido transcende o fornecimento pontual. Os melhores parceiros atuam como co-desenvolvedores, participando desde a concepção da peça com sugestões de alterações no desenho que facilitem a fundição e reduzam custos sem comprometer a funcionalidade. Programas de melhoria contínua baseados em ferramentas como kaizen, Six Sigma e análise de modo e efeito de falha (FMEA) de processo são diferenciais competitivos. O fornecedor ideal apresenta evidências de redução anual de refugo, aumento de produtividade e iniciativas de redução de peso das peças, contribuindo para a meta de eficiência energética e sustentabilidade do cliente automotivo."),
], [
    ("Quais certificações são obrigatórias para fornecedores automotivos de ferro fundido?",
     "A certificação primária é a IATF 16949, específica para fornecedores da indústria automotiva. Adicionalmente, a ISO 9001 é requisito base, e certificações ambientais como ISO 14001 são cada vez mais exigidas por montadoras. Para peças de segurança, o fornecedor deve atender aos requisitos de PPAP nos níveis 3 ou 4."),
    ("Como o fabricante automotivo garante a rastreabilidade das peças fundidas?",
     "A rastreabilidade é garantida por sistema de codificação individual por peça, geralmente via marcação a laser ou pintura a jato de tinta com código datamatrix. Cada peça carrega informações de data de produção, turno, forno utilizado e resultados de ensaios, vinculados a um banco de dados que permite auditoria completa do histórico produtivo."),
    ("Qual a diferença entre ferro nodular e cinzento em aplicações automotivas?",
     "O ferro cinzento (GG25, GG30) é predominante em blocos de motor e cabeçotes por sua excelente condutividade térmica e capacidade de amortecimento de vibrações. O ferro nodular (GGG40, GGG50) é usado em componentes estruturais como suportes de suspensão e cubos de roda, onde a resistência mecânica e a ductilidade superiores são requisitos críticos de segurança."),
]))

ARTICLES.append((13, "fabricante-de-pecas-para-bombeamento-de-concreto", "Fabricante de peças para bombeamento de concreto: critérios técnicos de avaliação", [
    ("Resistência ao desgaste abrasivo em peças para bombeamento",
     "O concreto bombeado contém agregados como areia, brita e cimento que atuam como abrasivos sobre as superfícies internas dos equipamentos. Um fabricante de peças para bombeamento de concreto precisa dominar a metalurgia do ferro fundido branco de alto cromo, cuja microestrutura com carbonetos complexos proporciona dureza acima de 60 HRC. As peças mais críticas — como anéis de desgaste, rotores e revestimentos de tubulação — exigem tratamento térmico de austenitização e revenimento para equilibrar dureza e tenacidade. A avaliação do fornecedor deve incluir a medição da profundidade da camada endurecida e a uniformidade da dureza ao longo da geometria da peça."),
    ("Geometria e tolerâncias dimensionais em componentes de bombeamento",
     "O desempenho hidráulico de uma bomba de concreto depende diretamente da precisão geométrica de seus componentes fundidos. Um fabricante de peças para bombeamento de concreto qualificado opera com modelos 3D e simulação de solidificação para prever e compensar distorções térmicas durante o resfriamento. As folgas entre rotor e carcaça, por exemplo, devem ficar na faixa de 0,10 a 0,30 mm para manter a eficiência volumétrica acima de 85%. A verificação dimensional por braço de medição articulado ou máquina de medir tridimensional (MMT) com certificado RBC é procedimento obrigatório na liberação de cada lote."),
    ("Normas técnicas aplicáveis a peças fundidas para concreto",
     "A fabricação de componentes para bombeamento de concreto segue normas específicas que regulam desde a composição química até os ensaios mecânicos. A NBR NM 87 padroniza os requisitos para ferro fundido branco de alto cromo, enquanto a ASTM A532 define classes de ligas resistentes à abrasão. O fabricante de peças para bombeamento de concreto deve apresentar relatórios de ensaio de tração conforme NBR ISO 6892 e de dureza conforme NBR NM ISO 6506, todos realizados em laboratório acreditado pela Cgcre. A conformidade com essas normas protege o comprador contra falhas prematuras e garante a intercambialidade das peças no mercado."),
    ("Processo de fundição e controle de qualidade na produção",
     "A fundição de peças para bombeamento de concreto demanda controle rigoroso em cada etapa do processo. A moldagem em areia verde ou cura química deve ser dimensionada para suportar a alta temperatura do metal líquido sem deformações. A análise termográfica do molde antes do vazamento previne defeitos como rechape e inclusão de areia. O fabricante de peças para bombeamento de concreto ideal utiliza espectrômetro de emissão óptica para verificar a composição química a cada panela e realiza ensaios metalográficos para confirmar a proporção de carbonetos na matriz metálica. O índice de refugo interno abaixo de 5% é sinal de processo maduro e estável."),
    ("Suporte técnico e engenharia de aplicação",
     "A complexidade dos sistemas de bombeamento de concreto exige que o fabricante de peças para bombeamento de concreto ofereça suporte técnico especializado além da entrega do produto. A engenharia de aplicação deve ser capaz de analisar o desgaste das peças em campo, identificar o mecanismo de falha predominante — abrasão, erosão ou corrosão — e recomendar alterações na composição química ou no tratamento térmico para prolongar a vida útil. Fornecedores que disponibilizam desenhos técnicos em formato CAD e histórico de alterações de engenharia demonstram maturidade técnica e compromisso com a parceria de longo prazo."),
], [
    ("Qual a vida útil típica de peças fundidas para bombeamento de concreto?",
     "A vida útil varia conforme a pressão de operação, o traço do concreto e a frequência de uso. Em condições normais, anéis de desgaste em ferro branco de alto cromo duram entre 300 e 800 horas de bombeamento. Rotores e estatores apresentam substituição entre 500 e 1.200 horas. O monitoramento periódico da espessura permite a troca programada, evitando paradas emergenciais."),
    ("Como identificar um fabricante confiável de peças para bombeamento?",
     "Um fabricante confiável possui laboratório metalúrgico próprio, certificação ISO 9001, rastreabilidade por lote e estoque regulador de peças críticas. É recomendável solicitar referências de outras concreteiras e visitar a fundição para avaliar in loco os processos de controle de qualidade e a organização do parque fabril."),
    ("O ferro fundido branco é sempre a melhor opção para peças de desgaste?",
     "O ferro branco de alto cromo é a escolha padrão para abrasão severa, mas em aplicações com impacto intenso pode ser necessário usar ferro nodular austemperado (ADI) ou aços liga revestidos. A seleção do material ideal depende da análise do mecanismo de desgaste predominante em cada componente do sistema de bombeamento."),
]))

ARTICLES.append((14, "fabricante-de-pecas-para-maquinas-e-equipamentos", "Fabricante de peças para máquinas e equipamentos industriais em ferro fundido", [
    ("Diversidade de ligas de ferro fundido para aplicações industriais",
     "Um fabricante de peças para máquinas e equipamentos industriais deve dominar um espectro amplo de ligas ferrosas, pois cada aplicação exige propriedades mecânicas distintas. O ferro fundido cinzento é amplamente utilizado em bases de máquinas-ferramenta e carcaças de redutores por sua excelente capacidade de amortecimento de vibrações. O ferro nodular atende componentes sujeitos a cargas dinâmicas, como mancais e bielas. Já o ferro vermicular (CGI) combina resistência mecânica superior com boa condutividade térmica, sendo ideal para cabeçotes de prensas e cilindros hidráulicos de alta pressão. O fornecedor completo oferece simulação metalúrgica para determinar a liga ótima para cada peça."),
    ("Capacidade de usinagem e acabamento superficial",
     "Peças fundidas para máquinas e equipamentos industriais raramente são entregues brutas de fundição. Um fabricante de peças para máquinas e equipamentos com usinagem integrada reduz o lead time total e elimina problemas de responsabilidade entre fornecedores. A capacidade de realizar operações de fresamento, torneamento, furação e mandrilamento com tolerâncias dimensionais na faixa de IT7 a IT9 é requisito fundamental. A rugosidade superficial (Ra) inferior a 3,2 µm em superfícies de vedação e o controle de perpendicularidade e concentricidade dentro de 0,02 mm são diferenciais que impactam diretamente a qualidade do equipamento final."),
    ("Tratamentos térmicos e superficiais para peças industriais",
     "A performance de peças fundidas em equipamentos industriais frequentemente depende de tratamentos térmicos e superficiais aplicados após a usinagem. O fabricante de peças para máquinas e equipamentos deve oferecer opções como têmpera por indução em guias de deslizamento, cementação em engrenagens e eixos, e nitretação a plasma para componentes que exigem alta resistência ao desgaste com baixa distorção dimensional. O revenimento para alívio de tensões em peças de parede espessa previne trincas por tensões residuais de fundição. A rastreabilidade dos ciclos térmicos, com gráficos de temperatura registrados, é evidência de controle de processo maduro."),
    ("Projeto colaborativo e engenharia simultânea",
     "A indústria de máquinas e equipamentos beneficia-se enormemente quando o fabricante de peças para máquinas e equipamentos participa desde a fase de projeto. A engenharia simultânea permite otimizar a geometria da peça para o processo de fundição, eliminando ângulos vivos que dificultam o enchimento do molde e reduzindo a espessura de paredes sem comprometer a rigidez estrutural. A simulação de enchimento e solidificação com softwares como MAGMA ou ProCAST identifica potenciais rechupes e porosidades antes da fabricação do ferramental. Essa abordagem colaborativa reduz o tempo de desenvolvimento do equipamento em até 40% e evita retrabalhos onerosos na fase de protótipo."),
    ("Logística e fornecimento para linhas de produção contínua",
     "Paradas de linha por falta de peças fundidas representam o maior custo oculto na indústria de equipamentos. Um fabricante de peças para máquinas e equipamentos com gestão logística eficiente opera com contratos de fornecimento baseados em previsão rolling de 12 meses, com entregas semanais sincronizadas pela programação da usinagem. O uso de embalagens retornáveis projetadas especificamente para cada peça reduz danos no transporte e viabiliza o abastecimento sequenciado na linha de montagem. O indicador de fill rate superior a 99% e a capacidade de atender pedidos emergenciais em até 48 horas são critérios decisivos na seleção do fornecedor."),
], [
    ("Qual a vantagem do ferro fundido sobre o aço em máquinas industriais?",
     "O ferro fundido oferece amortecimento de vibrações até 10 vezes superior ao aço, o que é crítico para precisão em máquinas-ferramenta. Além disso, sua fluidez permite geometrias complexas em uma única peça fundida, reduzindo o número de juntas e pontos de falha. O custo por quilo da peça acabada também é menor, especialmente em grandes tiragens."),
    ("Como o fabricante de peças industriais lida com peças de grandes dimensões?",
     "Peças de grande porte, como bases de prensas que excedem 5 toneladas, exigem fornos de fusão de alta capacidade (10 t ou mais), pontes rolantes dimensionadas e sistemas de moldagem especiais. O fornecedor deve ter área de fundição ampla, equipamentos de manipulação automatizados e fornos de tratamento térmico proporcionais ao tamanho das peças."),
    ("A prototipagem rápida é viável para peças fundidas industriais?",
     "Sim, a manufatura aditiva de modelos para fundição (padrões impressos em 3D) permite protótipos em dias, não semanas. Combinada com simulação de solidificação, reduz o ciclo de desenvolvimento de 90 para 15 dias. Isso viabiliza ajustes de geometria antes da confecção do ferramental definitivo em aço."),
]))

ARTICLES.append((15, "fornecedor-aneis-de-segmento", "Fornecedor de anéis de segmento: como avaliar qualidade e capacidade técnica", [
    ("Metalurgia de precisão na fabricação de anéis de segmento",
     "O fornecedor de anéis de segmento deve demonstrar domínio absoluto da metalurgia do ferro fundido cinzento e nodular em formatos anelares de parede fina. A microestrutura requer grafita uniformemente distribuída em matriz perlítica ou martensítica, dependendo da posição do anel no pistão — primeiro, segundo ou raspador de óleo. O controle do teor de fósforo, entre 0,3% e 0,7%, é crítico para formar a rede de esteadita que confere resistência ao desgaste. A análise metalográfica por microscopia óptica deve confirmar a classificação do tamanho e distribuição da grafita conforme ASTM A247, sem a presença de carbonetos livres que fragilizariam o anel em operação."),
    ("Tolerâncias dimensionais e ovalização em segmentos de pistão",
     "Anéis de segmento operam com folgas da ordem de 0,01 mm dentro do canal do pistão, exigindo do fornecedor de anéis de segmento capacidade de usinagem de altíssima precisão. A tolerância de altura do anel (espessura axial) é tipicamente de ±0,005 mm, e a espessura radial deve variar menos de 0,008 mm ao longo da circunferência para garantir pressão uniforme contra a parede do cilindro. A ovalização máxima permitida após a abertura do anel é de 0,03 mm, medida em equipamento de projeção ampliada com resolução de 0,001 mm. O fornecedor qualificado utiliza retíficas CNC de dupla face com compensação automática de desgaste do rebolo para manter estas tolerâncias em produção seriada."),
    ("Ensaios funcionais e simulação de operação",
     "A qualidade de um anel de segmento só se confirma plenamente em condições dinâmicas. O fornecedor de anéis de segmento de referência dispõe de bancada de teste para medição da pressão tangencial distribuída, que deve seguir o perfil especificado no desenho. O ensaio de estanqueidade com iluminação de fundo revela a porcentagem de contato entre o anel e o cilindro mestre — índice mínimo de 85% para anéis de primeiro canal. O teste de fadiga por pulsação hidráulica acelera 10 milhões de ciclos para verificar a durabilidade do material. Resultados desses ensaios devem acompanhar cada lote como garantia de desempenho em campo."),
    ("Tratamento superficial e revestimentos tecnológicos",
     "A evolução dos motores modernos exige que o fornecedor de anéis de segmento ofereça opções de revestimento superficial para reduzir atrito e aumentar vida útil. A cromagem dura por banho eletrolítico, com espessura entre 0,05 e 0,15 mm, é o revestimento clássico para o primeiro canal. O revestimento por aspersão térmica de molibdênio proporciona resistência ao desgaste adesivo em condições de lubrificação marginal. Mais recentemente, o PVD (Physical Vapor Deposition) de nitreto de titânio ou DLC (Diamond-Like Carbon) tem sido aplicado em anéis de alta performance, reduzindo o coeficiente de atrito para valores abaixo de 0,10. O fornecedor deve especificar o revestimento adequado para cada aplicação."),
    ("Rastreabilidade e certificação na produção de segmentos",
     "O fornecedor de anéis de segmento da indústria automotiva e de motores estacionários opera com loteamento controlado desde a fusão até a expedição. Cada lote recebe um número único que rastreia a composição química do metal, os parâmetros de tratamento térmico e os resultados de ensaios dimensionais e funcionais. A certificação ISO 9001 com escopo específico para anéis de pistão é o padrão mínimo, mas fornecedores que atendem motores de grande porte ou aplicações militares também possuem AS 9100 ou IATF 16949. O relatório de ensaio 3.1 conforme EN 10204 é exigido para cada lote, garantindo a conformidade com as especificações contratadas."),
], [
    ("Qual a diferença entre anéis de segmento fundidos e usinados?",
     "Anéis de segmento são sempre usinados após a fundição, mas o processo de obtenção do blank difere: anéis fundidos em forma de anel contínuo (circulares) ou em barras que depois são abertas. A fundição em anéis individuais é preferida para grandes volumes, enquanto barras fundidas são usadas para produção de pequenos lotes ou anéis de grandes diâmetros."),
    ("Como identificar um anel de segmento de baixa qualidade?",
     "Sinais de baixa qualidade incluem rebarbas nas bordas, variação visível de espessura ao longo da circunferência, superfície com porosidades ou inclusões, tensão tangencial irregular e baixo percentual de contato no ensaio de estanqueidade (abaixo de 70%). A ausência de identificação do lote na embalagem também é indicador de rastreabilidade deficiente."),
    ("Com que frequência os anéis de segmento devem ser substituídos?",
     "A substituição depende da aplicação e das condições de operação. Em motores automotivos de passeio, a troca ocorre tipicamente entre 100.000 e 150.000 km. Em motores estacionários a gás, a vida útil varia de 8.000 a 20.000 horas. A medição da abertura do anel no cilindro é o indicador mais confiável para determinar o momento ideal da substituição."),
]))

ARTICLES.append((16, "fundicao-de-auto-pecas", "Fundição de autopeças: processo produtivo e vantagens do ferro fundido", [
    ("Etapas do processo produtivo na fundição de autopeças",
     "A fundição de autopeças em ferro fundido inicia com a seleção e pesagem dos materiais metálicos que compõem a carga do forno. Sucata de aço, retorno de fundição e ligas ferro-silício-magnésio são fundidos em fornos de indução de média frequência, onde a temperatura atinge 1.450 °C. O metal líquido é transferido para a panela de vazamento, onde recebe o tratamento nodulizante para produção de ferro nodular. A moldagem em areia verde ou cura química forma a cavidade que reproduz o negativo da peça. Cada etapa é monitorada por sistemas de automação que registram variáveis como temperatura, tempo de vazamento e pressão de compactação do molde, garantindo repetibilidade entre lotes."),
    ("Vantagens do ferro fundido sobre outros materiais em autopeças",
     "O ferro fundido apresenta uma combinação única de propriedades que o torna o material preferido para uma ampla gama de autopeças. Sua capacidade de amortecimento vibratório é até 20 vezes superior ao aço, o que reduz ruído e vibração em componentes como blocos de motor e carcaças de transmissão. A fluidez do metal líquido permite preencher geometrias complexas com paredes finas, viabilizando designs que seriam impossíveis ou muito caros em aço forjado. Além disso, a condutividade térmica do ferro cinzento, da ordem de 50 W/m·K, facilita a dissipação de calor em componentes como cabeçotes e discos de freio, contribuindo para maior durabilidade do motor."),
    ("Controle de qualidade em cada etapa da fundição",
     "A fundição de autopeças implementa controle de qualidade em todas as fases do processo produtivo. Na recepção da matéria-prima, a sucata metálica passa por inspeção visual e análise química por espectrometria para rejeitar contaminantes. Durante a fusão, amostras são coletadas a cada 30 minutos para verificação da composição química e temperatura. Após a desmoldagem, as peças passam por jateamento de granalha para limpeza superficial e inspeção visual 100% para identificação de defeitos como rechape, sopro e inclusão de areia. Peças críticas para segurança, como componentes de freio e direção, são submetidas a ensaio de líquido penetrante e raio-X digital, com laudo individual arquivado por no mínimo 10 anos."),
    ("Tipos de autopeças produzidas em ferro fundido",
     "A versatilidade do ferro fundido permite que a fundição de autopeças atenda a praticamente todos os sistemas do veículo. No trem de força, os blocos de motor em ferro cinzento GGV30 e os cabeçotes em ferro nodular GGG40 são os exemplos mais emblemáticos. No sistema de freios, discos e tambores em ferro cinzento perlítico com grafita tipo A garantem dissipação térmica eficiente e desgaste uniforme. Componentes de suspensão como braços de controle e suportes de amortecedor em ferro nodular perlítico oferecem resistência mecânica superior a 500 MPa. No sistema de transmissão, carcaças de caixa de câmbio e diferenciais em ferro cinzento GG25 proporcionam rigidez e estabilidade dimensional."),
    ("Sustentabilidade e economia circular na fundição automotiva",
     "A fundição de autopeças destaca-se como exemplo de economia circular na indústria. A sucata de aço e o retorno de fundição — canais de alimentação, massalotes e peças refugadas — representam entre 60% e 80% da carga do forno, reduzindo drasticamente a necessidade de minério de ferro virgem. O consumo energético médio de 0,6 kWh por quilo de metal fundido em fornos de indução modernos é significativamente inferior ao de aciarias. Além disso, as peças fundidas são 100% recicláveis ao final da vida útil: um bloco de motor pode ser refundido para produzir novos blocos sem perda de qualidade, fechando o ciclo com emissões de CO₂ reduzidas em até 60% frente ao uso de materiais primários."),
], [
    ("Quais autopeças não podem ser fabricadas por fundição?",
     "Elementos de fixação como parafusos, porcas e molas não são fabricados por fundição devido às altas solicitações mecânicas e necessidade de fluxo de fibras, sendo produzidos por forjamento ou estamparia. Componentes eletrônicos e sensores também são excluídos por suas especificidades de materiais semicondutores."),
    ("Quanto tempo leva o ciclo produtivo de uma autopeça fundida?",
     "O ciclo completo, da fusão à peça acabada usinada, varia de 3 a 15 dias úteis. A fundição em si — vazamento, solidificação e desmoldagem — leva de 2 a 24 horas. O tratamento térmico adiciona 1 a 3 dias, e a usinagem final pode levar de 1 a 8 dias conforme a complexidade geométrica da peça."),
    ("A fundição de autopeças atende à produção de baixo volume?",
     "Sim, o processo de moldagem em areia permite produção de 10 a 10.000 peças por mês com custo competitivo. Para volumes muito baixos, a fundição em molde manual ou modelos impressos em 3D reduz o custo de ferramental. Para altos volumes, a moldagem em linha automatizada com até 300 moldes por hora é a solução mais eficiente."),
]))

ARTICLES.append((17, "fundicao-de-autopecas", "Fundição de autopeças: especificações técnicas e controle de qualidade", [
    ("Especificações dimensionais e classes de tolerância",
     "A fundição de autopeças opera com classes de tolerância rigorosas definidas por normas internacionais. A ISO 8062 estabelece os desvios admissíveis para dimensões lineares em peças fundidas, com classes que variam de CT7 a CT12 conforme o processo de moldagem e o material. Para autopeças típicas, como suportes de motor e braços de suspensão, a classe CT9 é comum, admitindo desvios de ±0,5 a ±1,5 mm para dimensões de até 100 mm. A fundição de precisão com machos de cura química atinge classes CT7 a CT8, com desvios de ±0,3 a ±0,8 mm, adequados para superfícies que dispensam usinagem posterior. O plano de inspeção define quais cotas são verificadas por CEP e quais por medição 100%."),
    ("Controle de composição química e microestrutura",
     "O laboratório metalúrgico de uma fundição de autopeças realiza análise química por espectrometria de emissão óptica em cada panela de metal líquido antes do vazamento. Os elementos monitorados incluem carbono equivalente (CE), silício, manganês, fósforo, enxofre, cromo, cobre e magnésio residual. Para ferro nodular, o teor de magnésio residual entre 0,03% e 0,06% é crítico para garantir a esferoidização completa da grafita. A metalografia quantitativa por análise de imagem digital mede o tamanho e a distribuição dos nódulos conforme ASTM E2567, com exigência típica de nodularidade mínima de 85% e contagem de nódulos acima de 100 por mm². O relatório metalográfico acompanha cada lote como certificado de conformidade."),
    ("Propriedades mecânicas e ensaios de tração",
     "A fundição de autopeças valida suas peças através de ensaios mecânicos realizados em corpos de prova extraídos de peças representativas de cada lote de produção. O ensaio de tração conforme NBR ISO 6892 determina o limite de escoamento, limite de resistência e alongamento. Para ferro nodular GGG50, os valores mínimos típicos são 350 MPa de escoamento, 500 MPa de resistência e 7% de alongamento. O ensaio de dureza Brinell, realizado em todas as peças de segurança via escleroscópio portátil ou durômetro de bancada, verifica a uniformidade da matriz metálica. A dureza esperada para ferro nodular perlítico está na faixa de 180 a 240 HB, desvio acima disso indica anormalidade no tratamento térmico que requer investigação."),
    ("Ensaio de estanqueidade e porosidade em autopeças",
     "Peças que operam sob pressão, como cabeçotes, carcaças de bomba de óleo e corpos de válvula, exigem ensaio de estanqueidade na fundição de autopeças. O método mais comum é o ensaio pneumático submerso, onde a peça é pressurizada com ar comprimido a 1,5 vezes a pressão de operação e submersa em tanque de água para detecção visual de bolhas. Para maior sensibilidade, utiliza-se o ensaio de vácuo com amônia ou o ensaio por espectrometria de massa com hélio, capaz de detectar vazamentos da ordem de 10⁻⁶ mbar·L/s. A porosidade interna, quando identificada por raio-X digital ou tomografia computadorizada, é classificada por tamanho e localização conforme norma interna, e peças com poros em regiões de vedação ou alta tensão são automaticamente rejeitadas."),
    ("Rastreabilidade documental e auditoria de processo",
     "A rastreabilidade na fundição de autopeças é assegurada por um sistema de gestão da qualidade que integra todos os registros de produção. Cada peça recebe uma marcação indelével contendo código de fundição, data de produção e sequencial do lote. Este código permite acessar o histórico completo: número da corrida de fusão, composição química, parâmetros de tratamento térmico, resultados de ensaios mecânicos e não destrutivos, e dados dimensionais. A auditoria interna periódica verifica a aderência aos procedimentos operacionais padrão e à política da qualidade. Clientes automotivos realizam auditorias de segunda parte para homologar a fundição como fornecedor, avaliando in loco a capacidade do processo e a conformidade documental."),
], [
    ("O que significa nodularidade mínima de 85% no ferro nodular?",
     "Nodularidade é o percentual de partículas de grafita que apresentam forma esférica em relação ao total de partículas na microestrutura. O mínimo de 85% garante que a grafita está predominantemente nodular, conferindo ductilidade e resistência ao ferro. Abaixo desse valor, a presença de grafita laminar reduz drasticamente a tenacidade e o alongamento do material."),
    ("Qual a diferença entre ensaio destrutivo e não destrutivo na fundição?",
     "Ensaios destrutivos como tração e dobramento são realizados em corpos de prova representativos do lote, sacrificando a peça ensaiada. Ensaios não destrutivos como raio-X e ultrassom inspecionam cada peça sem danificá-la. A combinação dos dois é obrigatória para peças de segurança automotiva."),
    ("Por que a dureza Brinell é o ensaio mais usado em autopeças fundidas?",
     "O ensaio Brinell é preferido por sua simplicidade, baixo custo e boa correlação com a resistência à tração no ferro fundido. A esfera de 10 mm com carga de 3.000 kgf produz uma impressão grande o suficiente para representar a microestrutura heterogênea do ferro fundido, diferentemente do Rockwell que mede apenas uma área localizada."),
]))

ARTICLES.append((18, "fundicao-de-ferro-cinzento-e-nodular", "Fundição de ferro cinzento e nodular: diferenças, aplicações e normas técnicas", [
    ("Diferenças microestruturais entre ferro cinzento e nodular",
     "A principal diferença entre ferro cinzento e nodular está na morfologia da grafita. No ferro cinzento, a grafita apresenta-se na forma de lamelas ou escamas, criando concentradores de tensão que reduzem a resistência e o alongamento. Já no ferro nodular, a grafita assume forma esferoidal, com nódulos que interrompem minimamente a continuidade da matriz metálica, resultando em resistência mecânica significativamente maior. A obtenção de cada microestrutura depende do tratamento do metal líquido: o ferro cinzento não recebe inoculação com magnésio ou cério, enquanto o nodular recebe tratamento nodulizante que promove a precipitação da grafita em nódulos. A matriz metálica de ambos pode ser modificada por tratamento térmico para ferritas, perlítica, martensítica ou austemperada."),
    ("Propriedades mecânicas comparadas: resistência e ductilidade",
     "O ferro nodular oferece resistência mecânica superior em todas as classes. Enquanto o ferro cinzento GG25 apresenta limite de resistência à tração de 250 MPa e alongamento desprezível (inferior a 1%), o ferro nodular GGG50 atinge 500 MPa com alongamento de 7% a 10%. A tenacidade à fratura do ferro nodular é de 10 a 30 vezes maior que a do cinzento, tornando-o adequado para componentes sujeitos a impacto e cargas cíclicas. No entanto, a capacidade de amortecimento vibratório do ferro cinzento é até 10 vezes superior, explicando sua preferência em bases de máquinas e blocos de motor. Um projeto de fundição de ferro cinzento e nodular bem-sucedido escolhe o material com base no equilíbrio entre estas propriedades para cada aplicação específica."),
    ("Normas técnicas para ferro cinzento e nodular no Brasil",
     "No Brasil, a fundição de ferro cinzento e nodular segue as normas ABNT NBR e suas correspondentes internacionais ASTM e ISO. Para ferro cinzento, a NBR 6589 classifica os materiais de GG10 a GG40, com limite de resistência à tração indicado pelo número (GG25 = 250 MPa mínimos). Para ferro nodular, a NBR 6916 define as classes de GGG40 a GGG80, incluindo as variantes austemperadas (ADI). As normas especificam composição química, propriedades mecânicas mínimas e procedimentos de ensaio. A ASTM A48 para cinzento e ASTM A536 para nodular são amplamente referenciadas em contratos de fornecimento. A conformidade com estas normas é verificada por laboratórios acreditados e documentada em certificados de ensaio."),
    ("Aplicações típicas de cada tipo de ferro fundido",
     "O ferro cinzento domina aplicações onde amortecimento de vibrações, condutividade térmica e custo são prioritários: blocos de motor automotivos e estacionários, discos de freio, carcaças de bombas e compressores, bases de máquinas-ferramenta e tambores de freio. O ferro nodular é o material de escolha para componentes estruturais que exigem resistência e tenacidade: suportes de suspensão automotiva, engrenagens, polias, mancais, bielas, componentes de máquinas agrícolas e rodoviárias, tubulações de grande diâmetro e componentes de energia eólica. A fundição de ferro cinzento e nodular permite que uma mesma fundição atenda segmentos industriais distintos com o mesmo processo base, variando apenas os parâmetros de fusão e tratamento do metal."),
    ("Inoculação e tratamento térmico: controle da microestrutura",
     "A inoculação é a etapa crítica que define as propriedades finais na fundição de ferro cinzento e nodular. No ferro cinzento, a inoculação com ferrosilício 75% controla o tamanho e distribuição das lamelas de grafita, evitando grafita tipo D ou E que prejudicam as propriedades mecânicas. No ferro nodular, a inoculação secundária após o tratamento nodulizante refina o tamanho dos nódulos e aumenta sua contagem. O tratamento térmico posterior permite transformar a matriz metálica: a ferritização produz ferro nodular ferrítico (GGG40), macio e tenaz; a perlização com resfriamento controlado gera GGG50 e GGG60, mais duros e resistentes; e o austemperamento produz ferro ADI, com resistência acima de 1.000 MPa e excelente resistência ao desgaste."),
], [
    ("É possível converter um projeto de ferro cinzento para nodular?",
     "Sim, mas requer revisão completa do projeto. O ferro nodular exige tolerâncias dimensionais diferentes devido à contração de solidificação de 0,8% a 1,2% contra 0,3% a 0,6% do cinzento. As espessuras de parede também devem ser reavaliadas, pois o nodular permite paredes mais finas devido à maior resistência. O custo da peça em nodular é 20% a 40% maior."),
    ("Qual ferro fundido é mais fácil de usinar?",
     "O ferro cinzento é mais fácil de usinar que o nodular. A grafita lamelar atua como lubrificante natural na interface ferramenta-peça, reduzindo o atrito e o desgaste da ferramenta de corte. O ferro nodular requer ferramentas de metal duro ou cerâmica e velocidades de corte 20% menores para a mesma vida útil da ferramenta."),
    ("Como identificar visualmente se uma peça é de ferro cinzento ou nodular?",
     "O ferro cinzento fraturado apresenta superfície de cor cinza-escura, aspecto granulado e quebra frágil sem deformação. O ferro nodular apresenta fratura com aspecto fibroso e clara deformação plástica antes da ruptura. Outro teste simples: o cavaco de usinagem do cinzento é quebradiço e pulverulento, enquanto o do nodular forma cavacos contínuos e enrolados."),
]))

ARTICLES.append((19, "fundicao-de-ferro-em-itaquaquecetuba", "Fundição de ferro em Itaquaquecetuba: estrutura industrial e capacidade produtiva", [
    ("Localização estratégica e logística industrial",
     "Uma fundição de ferro em Itaquaquecetuba beneficia-se de localização privilegiada no Alto Tietê, a 35 km do centro de São Paulo e com acesso direto às rodovias Ayrton Senna e Dutra. Esta posição geográfica permite atender clientes na Grande São Paulo, Vale do Paraíba e litoral com prazos de entrega reduzidos. A proximidade com o Porto de Santos facilita a importação de matérias-primas como sucata de alta qualidade e ligas metálicas, além da exportação de peças acabadas para América Latina. A malha rodoviária que conecta a região às principais capitais do Sudeste torna o custo logístico competitivo, especialmente para peças de grande porte cujo frete representa parcela significativa do custo total."),
    ("Infraestrutura fabril e capacidade de fusão",
     "A infraestrutura de uma fundição de ferro em Itaquaquecetuba moderna inclui fornos de indução de média frequência com capacidade de fusão de 3 a 10 toneladas por turno, dependendo da configuração. A área construída típica varia de 5.000 a 15.000 m², abrangendo setores de preparação de areia, moldagem, fusão, desmoldagem, jateamento, usinagem e expedição. Pontes rolantes com capacidade de 5 a 20 toneladas percorrem toda a extensão do galpão, transportando panelas de metal líquido, moldes e peças acabadas. A subestação de energia elétrica dimensionada para demandas de 2.000 a 5.000 kVA garante operação ininterrupta dos fornos, mesmo durante picos de produção na indústria automotiva e de bens de capital."),
    ("Sistemas de moldagem e tipos de processo",
     "A fundição de ferro em Itaquaquecetuba utiliza sistemas de moldagem variados conforme o perfil produtivo de cada cliente. A moldagem em areia verde em linhas automatizadas tipo disamatic ou hunter é predominante para peças seriadas de pequeno e médio porte, com capacidade de 80 a 250 moldes por hora. Para peças de grande porte ou baixo volume, a moldagem manual em caixa e a moldagem em cura química com resina furânica ou fenólica oferecem flexibilidade dimensional. A macharia em caixa fria (cold box) com amina produz machos de alta precisão para geometrias internas complexas. A versatilidade de processos permite que uma única fundição atenda desde autopeças de 0,5 kg até componentes industriais de 500 kg."),
    ("Controle ambiental e certificações de sustentabilidade",
     "Fundições modernas instaladas na região investem continuamente em sistemas de controle ambiental. Os fornos de indução são equipados com exaustores e filtros manga que capturam particulados metálicos, mantendo as emissões dentro dos limites da CETESB. A areia de fundição usada é regenerada termicamente ou mecanicamente para reutilização, reduzindo em até 95% o volume de resíduos destinados a aterros. Uma fundição de ferro em Itaquaquecetuba comprometida com a sustentabilidade também trata e recircula a água de resfriamento dos fornos, diminuindo o consumo hídrico em 80%. A certificação ISO 14001 é o padrão mínimo, e fornecedores que atendem clientes internacionais possuem também ISO 50001 de eficiência energética."),
    ("Capacidade de usinagem e entrega de peças acabadas",
     "O parque de usinagem integrado diferencia uma fundição de ferro em Itaquaquecetuba que entrega peças prontas para montagem. Centros de usinagem CNC de 3 a 5 eixos realizam operações de fresamento, torneamento, furação e mandrilamento com tolerâncias de até IT6. A capacidade de retífica plana e cilíndrica permite acabamento superficial Ra inferior a 0,8 µm em superfícies de vedação. A pintura eletrostática ou por imersão protege as peças contra corrosão durante o transporte e armazenamento. A integração fundição-usinagem reduz o lead time total em até 30%, elimina o custo logístico de transporte de peças brutas entre fornecedores e simplifica a gestão da qualidade com responsabilidade única."),
], [
    ("Quais são as vantagens de contratar uma fundição em Itaquaquecetuba?",
     "As principais vantagens são: localização estratégica com acesso às principais rodovias do estado, proximidade de indústrias automotivas e de bens de capital no ABCD e Vale do Paraíba, disponibilidade de mão de obra técnica especializada na região, e infraestrutura logística que reduz prazos de entrega em 1 a 2 dias úteis comparado a fornecedores do interior."),
    ("Que tipo de peças são produzidas nas fundições de Itaquaquecetuba?",
     "A região produz desde pequenas autopeças como suportes e terminais até componentes industriais de grande porte como bases de prensas e carcaças de redutores. O perfil produtivo é diversificado, incluindo ferro cinzento, nodular e ligas especiais para os setores automotivo, agrícola, construção civil e mineração."),
    ("É possível visitar a fundição antes de fechar contrato?",
     "Sim, a maioria das fundições recebe visitas técnicas mediante agendamento. A visita permite avaliar a organização do chão de fábrica, as condições dos equipamentos, as práticas de segurança e a limpeza ambiental. É também a oportunidade de verificar in loco a capacidade de produção e a qualidade dos sistemas de controle de processo."),
]))

ARTICLES.append((20, "fundicao-de-ferro-em-pep-set", "Fundição de ferro em pep set: processo, vantagens e aplicações industriais", [
    ("O que é o processo pep set e como funciona",
     "A fundição de ferro em pep set, também conhecida como moldagem em cura química com resina fenólica-uretânica, utiliza um sistema de duas partes: uma resina fenólica e um isocianato, que reagem na presença de um catalisador gasoso (amina terciária) para curar a areia instantaneamente. O processo ocorre em três etapas: mistura da areia com os ligantes, sopro da areia contra o modelo para formar o molde, e passagem do gás catalisador através da areia compactada. A cura ocorre em segundos, permitindo a desmoldagem imediata do modelo e a reutilização da caixa de moldagem para o próximo ciclo. A fundição de ferro em pep set destaca-se pela alta produtividade e pela excelente definição superficial das peças."),
    ("Vantagens produtivas do pep set para fundição de ferro",
     "A principal vantagem da fundição de ferro em pep set é a velocidade do ciclo de moldagem. Enquanto a moldagem em areia verde exige de 4 a 24 horas para que o molde ganhe resistência suficiente, o pep set cura em 5 a 30 segundos, permitindo a produção de centenas de moldes por hora em equipamentos automáticos. A precisão dimensional é superior à areia verde, com classes de tolerância CT7 a CT9. O acabamento superficial resultante é mais liso, reduzindo a necessidade de usinagem posterior. Outra vantagem significativa é a menor geração de refugo por defeitos de moldagem, já que o molde curado é rígido e não deforma durante a manipulação e o vazamento do metal."),
    ("Aplicações industriais da fundição pep set",
     "A fundição de ferro em pep set é particularmente adequada para peças de médio e grande porte que exigem boa precisão dimensional e acabamento superficial superior ao da areia verde. As aplicações típicas incluem carcaças de bombas industriais, corpos de válvulas para a indústria petroquímica, componentes de máquinas agrícolas como carcaças de transmissão, peças para compressores, e componentes de equipamentos de movimentação de terra. O processo também é amplamente utilizado na produção de machos complexos para o setor automotivo, onde os canais internos de refrigeração de cabeçotes e blocos de motor exigem geometrias intrincadas que só o pep set consegue reproduzir com precisão."),
    ("Comparação com outros processos de moldagem",
     "Ao comparar a fundição de ferro em pep set com a moldagem em areia verde, as diferenças são marcantes. O pep set oferece precisão dimensional 30% superior e acabamento superficial mais liso, mas com custo de ligante 15% a 25% maior. Contra a moldagem em cura química com resina furânica, o pep set é mais rápido (segundos contra horas de cura) e não gera gases tóxicos de SO₂ durante a cura. Em comparação com a macharia shell molding, o pep set permite geometrias mais complexas e maior produtividade, embora o shell molding ofereça acabamento superficial ainda melhor. A escolha entre processos depende do volume de produção, da complexidade geométrica e dos requisitos dimensionais de cada peça."),
    ("Controle de gases e segurança na operação pep set",
     "A operação da fundição de ferro em pep set requer cuidados específicos com segurança ocupacional. O gás catalisador utilizado — trietilamina (TEA) ou dimetiletilamina (DMEA) — é inflamável e tóxico, exigindo sistemas de exaustão fechados e cortinas de ar nas áreas de injeção de gás. Sensores de detecção de amina monitoram continuamente a concentração no ambiente de trabalho, que deve permanecer abaixo do limite de tolerância de 10 ppm estabelecido pela NR-15. A operação correta inclui a purga do molde com ar comprimido após a cura para remover resíduos de gás antes do vazamento do metal. O tratamento dos efluentes gasosos é feito por lavadores de gases ou queimadores térmicos, garantindo a conformidade com a legislação ambiental."),
], [
    ("O pep set é mais caro que a moldagem em areia verde?",
     "Sim, o custo por molde é 15 a 25% maior devido ao valor dos ligantes fenólicos e do gás catalisador. No entanto, este custo adicional é frequentemente compensado pela redução de refugo, menor necessidade de usinagem e maior produtividade. Para peças que exigem precisão dimensional, o pep set é economicamente vantajoso."),
    ("Que tipos de ligantes são usados no pep set?",
     "O sistema utiliza dois componentes: uma resina fenólica (Parte 1) e um poliisocianato (Parte 2), misturados à areia na proporção típica de 1,2% a 1,8% em peso cada. A cura é promovida pela passagem de catalisador gasoso à base de amina terciária (TEA ou DMEA), que polimeriza a resina instantaneamente."),
    ("O pep set permite produção de peças de grande porte?",
     "Sim, o processo é amplamente usado para peças de até 500 kg ou mais. A resistência do molde curado é alta, suportando o peso do metal líquido sem deformação. Para peças muito grandes, a cura pode ser feita em seções, combinando pep set com montagem manual de machos, garantindo a viabilidade técnica de componentes de grande porte."),
]))

ARTICLES.append((21, "fundicao-de-ferro-fundido-2", "Fundição de ferro fundido: processo completo da matéria-prima à peça acabada", [
    ("Recepção e preparação da matéria-prima na fundição",
     "O processo de fundição de ferro fundido começa muito antes da fusão, na recepção e preparação criteriosa das matérias-primas. A sucata de aço, principal componente da carga, passa por segregação por tipo e análise química por espectrometria portátil para rejeitar contaminantes como cobre, estanho e cromo em teores acima do especificado. O retorno de fundição — canais, massalotes e peças refugadas — é britado e limpo por separação magnética para remover areia aderida. O gusa de alto-forno, quando utilizado, é armazenado em pátio coberto para evitar contaminação por umidade. A dosagem precisa de cada componente é realizada por balanças eletrônicas com precisão de 0,5%, formando a carga que alimentará o forno de indução."),
    ("Fusão e tratamento do metal líquido",
     "A fusão na fundição de ferro fundido ocorre em fornos de indução de média frequência (200 a 1.000 Hz), onde a corrente elétrica induzida no metal gera calor por efeito Joule. A temperatura da carga sólida eleva-se até 1.450-1.550 °C, dependendo da composição química desejada. Amostras são coletadas a cada 30 minutos para análise em espectrômetro de emissão óptica, ajustando-se a composição com adição de ferro-ligas. Para produção de ferro nodular, o metal líquido é transferido para a panela de tratamento, onde recebe a adição de liga nodulizante à base de magnésio. A inoculação com ferrosilício 75% é realizada momentos antes do vazamento para controlar a nucleação da grafita. O controle rigoroso da temperatura de vazamento, entre 1.350 e 1.420 °C, é fundamental para a qualidade da peça."),
    ("Moldagem e vazamento: da cavidade à peça bruta",
     "Com o metal líquido preparado, a fundição de ferro fundido prossegue para a etapa de moldagem e vazamento. O molde, fabricado em areia aglomerada com bentonita ou resina, contém a cavidade com o formato da peça desejada. A areia é compactada por equipamentos automáticos de moldagem que garantem densidade uniforme. Machos de areia com curados criam as cavidades internas da peça. O metal líquido é vazado no molde através dos canais de alimentação, preenchendo a cavidade e os massalotes, que compensam a contração de solidificação. O tempo de vazamento varia de segundos a minutos conforme o tamanho da peça. A solidificação ocorre da parede do molde para o centro da peça, com resfriamento controlado que define a microestrutura final do ferro fundido."),
    ("Desmoldagem, rebarbação e tratamento térmico",
     "Após a solidificação e resfriamento completo, a peça é retirada do molde na etapa de desmoldagem. Na fundição de ferro fundido, este processo é mecanizado por grelhas vibratórias que separam a areia da peça metálica. A areia usada segue para o sistema de regeneração. A peça bruta, ainda com canais e massalotes, passa pela rebarbação — remoção dos excessos de metal por esmerilhamento, maçarico de corte térmico ou prensa hidráulica. O jateamento de granalha de aço limpa a superfície da peça, removendo areia sinterizada e óxidos. O tratamento térmico, quando especificado, é realizado em fornos elétricos de temperatura controlada: recozimento para alívio de tensões, normalização para refino de grão, ou austemperamento para produção de ferro ADI."),
    ("Usinagem final, inspeção e expedição",
     "A etapa final da fundição de ferro fundido integra usinagem de precisão e inspeção dimensional para entrega de peças prontas para montagem. Centros de usinagem CNC realizam as operações de acabamento nas superfícies funcionais, com tolerâncias dimensionais que podem chegar a ±0,02 mm. A inspeção final verifica 100% das cotas críticas e realiza ensaios não destrutivos conforme especificação do cliente: líquido penetrante, partículas magnéticas ou raio-X digital. As peças aprovadas recebem marcação de rastreabilidade e proteção anticorrosiva por óleo solúvel ou pintura. A expedição é organizada por lote, acompanhada do certificado de qualidade e relatórios de ensaio, garantindo que cada peça entregue atende exatamente às especificações contratadas."),
], [
    ("Quanto tempo leva todo o processo de fundição?",
     "O ciclo completo, da recepção da matéria-prima à peça usinada pronta para embarque, varia de 5 a 20 dias úteis. A fusão e moldagem levam de 2 a 48 horas. O tratamento térmico adiciona 1 a 4 dias. A usinagem e inspeção final consomem de 2 a 10 dias, dependendo da complexidade dimensional e dos requisitos de ensaio."),
    ("Qual a taxa de refugo típica em uma fundição?",
     "Fundições bem gerenciadas operam com refugo entre 3% e 7% do total produzido. Defeitos comuns incluem rechape (contração), sopro (gases), inclusão de areia e porosidade. Cada ponto percentual de refugo representa custo direto de material e energia, sendo monitorado e atacado continuamente por programas de melhoria."),
    ("O ferro fundido pode ser reciclado infinitamente?",
     "Sim, o ferro fundido é 100% reciclável e pode ser refundido inúmeras vezes sem perda de qualidade. A sucata de retorno da própria fundição e as peças descartadas pelos clientes retornam ao forno como carga. Esta característica torna o ferro fundido um material permanentemente circular e ambientalmente superior a muitos materiais descartáveis."),
]))

ARTICLES.append((22, "fundicao-de-ferro-fundido", "Fundição de ferro fundido cinzento e nodular: guia técnico completo", [
    ("Classificação e nomenclatura dos ferros fundidos",
     "A fundição de ferro fundido cinzento e nodular utiliza sistemas de classificação padronizados internacionalmente. O ferro cinzento é designado pela sigla GG seguida do limite de resistência à tração em MPa: GG20 (200 MPa), GG25 (250 MPa), GG30 (300 MPa) e GG35 (350 MPa). A nomenclatura europeia EN-GJL também é comum. O ferro nodular utiliza as designações GGG (EN-GJS) seguidas do limite de resistência e, em alguns padrões, do alongamento: GGG40 (resistência de 400 MPa e alongamento de 12%), GGG50 (500 MPa, 7%), GGG60 (600 MPa, 3%) e GGG70 (700 MPa, 2%). A seleção da classe correta depende das solicitações mecânicas, da temperatura de operação e dos requisitos de tenacidade de cada aplicação."),
    ("Metalurgia dos ferros fundidos: carbono equivalente e microestrutura",
     "O carbono equivalente (CE) é o parâmetro metalúrgico central na fundição de ferro fundido cinzento e nodular, calculado pela fórmula CE = %C + (%Si/3) + (%P/3). Para ferro cinzento, o CE típico está entre 3,8% e 4,3%, garantindo grafita lamelar tipo A em matriz perlítica ou ferrítica-perlítica. No ferro nodular, o CE situa-se entre 4,2% e 4,6%, e a presença de magnésio residual (0,03-0,06%) força a precipitação da grafita na forma esferoidal. A microestrutura resultante determina as propriedades do material: perlita proporciona dureza e resistência ao desgaste, ferrita oferece ductilidade, e austenita retida aparece em ferros austemperados de alta resistência."),
    ("Controle de contração e projeto de massalotes",
     "A contração de solidificação difere significativamente entre os dois tipos de ferro, exigindo projetos de massalote específicos na fundição de ferro fundido cinzento e nodular. O ferro cinzento contrai aproximadamente 0,3% a 0,6% durante a solidificação, enquanto o nodular contrai de 0,8% a 1,2% — quase o dobro. Esta maior contração exige massalotes de maior volume e posicionamento mais cuidadoso no ferro nodular para evitar rechupes internos. O software de simulação de solidificação calcula o módulo térmico de cada região da peça e dimensiona massalotes com volume 1,2 a 1,5 vezes o volume da contração prevista. A localização dos massalotes deve priorizar as regiões de maior massa térmica da peça, que solidificam por último."),
    ("Defeitos típicos e métodos de prevenção",
     "Cada tipo de ferro apresenta suscetibilidade a defeitos específicos que a fundição de ferro fundido cinzento e nodular deve prevenir. No ferro cinzento, o defeito mais comum é o sopro ou blowhole, causado por gases gerados durante o vazamento que não conseguem escapar pelo molde. A permeabilidade da areia e o sistema de ventilação adequado previnem este defeito. No ferro nodular, a principal preocupação é a degeneração nodular — perda da forma esferoidal da grafita devido a elementos antiesferoidizantes como titânio e chumbo, ou tempo excessivo entre inoculação e vazamento. O controle rigoroso da composição química e a inoculação tardia, feita segundos antes do vazamento, são as medidas preventivas mais eficazes."),
    ("Critérios de seleção entre ferro cinzento e nodular",
     "A decisão entre ferro cinzento e nodular no projeto de uma peça fundida baseia-se em cinco critérios técnicos. Primeiro, solicitação mecânica: sob tensões acima de 250 MPa ou cargas de impacto, o nodular é obrigatório. Segundo, amortecimento vibratório: o cinzento é 5 a 10 vezes superior. Terceiro, condutividade térmica: o cinzento conduz calor 30% melhor. Quarto, usinabilidade: o cinzento é mais fácil de usinar. Quinto, custo: ferro cinzento é 20 a 40% mais barato por quilo de peça acabada. A fundição de ferro fundido cinzento e nodular oferece ambas as opções, cabendo ao engenheiro de aplicação ponderar estes fatores para a escolha otimizada. Materiais intermediários como ferro vermicular (CGI) preenchem lacunas entre os dois extremos."),
], [
    ("Qual a diferença de custo entre ferro cinzento e nodular?",
     "O ferro nodular custa de 20% a 40% mais que o cinzento devido à adição de liga nodulizante (ferro-silício-magnésio), ao maior consumo de energia no tratamento e à menor produtividade na usinagem. A diferença se justifica quando a aplicação exige resistência mecânica superior ou tenacidade."),
    ("Ferro cinzento enferruja como o aço?",
     "Sim, ambos são ligas ferrosas e oxidam na presença de umidade. No entanto, o ferro cinzento forma uma camada de óxido mais aderente que em alguns casos protege o substrato. Para aplicações expostas, recomenda-se pintura anticorrosiva ou proteção por óleo. Ferros nodulares com matriz ferrítica podem apresentar oxidação ligeiramente inferior aos perlíticos."),
    ("É possível soldar ferro fundido cinzento ou nodular?",
     "Sim, mas a soldagem requer procedimentos especiais. O ferro cinzento é o mais difícil de soldar devido à grafita lamelar que fragiliza a zona termicamente afetada. Recomenda-se pré-aquecimento a 250-600 °C, uso de eletrodos de níquel (ENi-CI) e resfriamento lento. O ferro nodular solda-se melhor com eletrodos de aço inoxidável ou níquel-ferro, com pré-aquecimento de 150-300 °C."),
]))

ARTICLES.append((23, "fundicao-de-pecas-em-ferro-fundido", "Fundição de peças em ferro fundido: especificações, prazos e certificações", [
    ("Documentação técnica que acompanha o pedido de cotação",
     "Para solicitar orçamento a uma fundição de peças em ferro fundido, o comprador deve fornecer documentação técnica completa. O desenho técnico em formato CAD (STEP, IGES ou DXF) com todas as dimensões, tolerâncias e especificações de material é obrigatório. A norma de referência para o material — ASTM, ABNT ou ISO — deve ser indicada, assim como a classe de ferro desejada. Informações adicionais como acabamento superficial requerido, ensaios não destrutivos necessários e volume anual estimado ajudam a fundição a dimensionar o ferramental e o plano de inspeção. A especificação de prazos de entrega esperados e condições de pagamento completa o pacote técnico para uma cotação precisa e competitiva."),
    ("Prazos típicos de produção por tipo de peça",
     "Os prazos de entrega em uma fundição de peças em ferro fundido variam conforme a complexidade e o volume do pedido. Peças simples em ferro cinzento, como contrapesos e bases, têm lead típico de 15 a 25 dias úteis para o primeiro lote após aprovação do ferramental. Peças de média complexidade em ferro nodular, como suportes e carcaças, demandam de 20 a 40 dias úteis. Componentes críticos que exigem ensaios não destrutivos 100% e documentação de rastreabilidade individualizada, como peças de segurança automotiva, podem levar de 30 a 60 dias úteis. A confecção de modelos e caixas de macho adiciona de 15 a 45 dias ao prazo do primeiro lote, dependendo da complexidade do ferramental."),
    ("Certificações exigidas por setor industrial",
     "Cada setor industrial impõe requisitos de certificação específicos para a fundição de peças em ferro fundido. A indústria automotiva exige IATF 16949 e PPAP nível 3 para todas as peças de segurança e funcionalidade crítica. O setor de óleo e gás requer API Q1 ou ISO 29001, além de certificação de ensaios conforme API 6A ou 6D para válvulas e conexões. A indústria de equipamentos agrícolas e rodoviários aceita ISO 9001 com requisitos adicionais de durabilidade em campo. Para exportação para a União Europeia, a marcação CE conforme Diretiva de Máquinas 2006/42/EC é obrigatória. O fornecedor deve apresentar certificados válidos emitidos por organismo acreditado pelo INMETRO ou equivalente internacional."),
    ("Processo de aprovação de ferramental e amostras",
     "Antes da produção seriada, a fundição de peças em ferro fundido submete amostras do primeiro lote para aprovação do cliente. O processo segue etapas definidas: fundição das primeiras peças com o ferramental novo, usinagem quando aplicável, inspeção dimensional completa com relatório, ensaios metalúrgicos e mecânicos, e envio das amostras para validação do cliente. O cliente realiza a verificação dimensional em suas próprias instalações e testa a peça em condição de montagem. Aprovadas as amostras, um relatório de aprovação de ferramental é assinado por ambas as partes, liberando a produção em série. Este processo é crítico para evitar não conformidades que só seriam descobertas após centenas de peças produzidas."),
    ("Garantia de qualidade e assistência pós-venda",
     "Uma fundição de peças em ferro fundido comprometida com a qualidade oferece garantia contra defeitos de fundição por prazo definido contratualmente, tipicamente de 6 a 12 meses após a entrega. A garantia cobre rechupes, sopros, trincas de tensão e não conformidades dimensionais que impeçam a montagem ou operação da peça. Excluem-se danos causados por mau uso, alterações no projeto sem aprovação ou desgaste natural. A assistência pós-venda inclui análise de falhas em campo com emissão de relatório técnico, reposição emergencial de peças com defeito comprovado e suporte técnico para otimização do projeto na próxima rodada de fornecimento. Fornecedores que oferecem engenharia de aplicação como serviço agregado demonstram maturidade e compromisso com a parceria."),
], [
    ("Quais documentos são necessários para cotar peças fundidas?",
     "Os documentos essenciais são: desenho técnico em formato CAD (STEP, IGES ou DXF) com cotas e tolerâncias; especificação do material com classe e norma (ex: GGG50 conforme NBR 6916); volume anual estimado; requisitos de ensaio (raio-X, líquido penetrante, ultrassom); e prazo de entrega desejado para o primeiro lote."),
    ("Como é calculado o prazo de entrega de peças fundidas?",
     "O prazo é calculado somando-se: tempo de fabricação do ferramental (15-45 dias para o primeiro pedido), fusão e moldagem (2-5 dias), tratamento térmico (1-4 dias), usinagem (2-10 dias), ensaios e inspeção (1-3 dias), e transporte (1-5 dias). Peças sem ferramental novo têm prazo reduzido em 15 a 30 dias."),
    ("A fundição emite certificado de qualidade para cada lote?",
     "Sim, toda fundição certificada ISO 9001 ou IATF 16949 emite certificado de qualidade para cada lote. O documento inclui: número do lote, composição química, resultados de ensaios mecânicos, relatório de ensaios não destrutivos e declaração de conformidade com a especificação contratada. O certificado segue o formato 3.1 ou 3.2 conforme EN 10204."),
]))
