apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: NOME-DO-SISTEMA
  description: UMA LINHA COM VERBO SOBRE O QUE FAZ
  tags:
    - stack
    - criticidade
spec:
  type: service
  lifecycle: production
  owner: dono-pessoa
  system: orquestrador-v4
  dependsOn:
    - component:outra-peca
